{#
  Stresses the chunked-insert path: 50,000 rows materialized with a small
  spanner_insert_chunk_size, so the table build must issue several separate,
  primary-key-ordered INSERT commits instead of one oversized transaction. A
  single 50k-row insert would exceed Spanner's per-transaction mutation limit on
  real Spanner; chunking keeps each commit well under it.

  The rows are generated by cross-joining two smaller arrays because Spanner's
  GENERATE_ARRAY is capped at 16,000 elements (a single generate_array(1, 50000)
  errors). ids are contiguous 1..50000.
#}
{{ config(materialized='table', primary_key=['id'], meta={'spanner_insert_chunk_size': 10000}) }}
select a * 10000 + b + 1 as id
from unnest(generate_array(0, 4)) as a
cross join unnest(generate_array(0, 9999)) as b
